### ISSUE TITLE
HTML Rendering Problem

### ISSUE THREAD

**Issue by devkapupara** [blinkfox/typora-vue-theme#14]
First of all, thank you for this awesome theme. It was just the type of dark theme I was looking for. I noticed a weird HTML rendering issue. I created a normal H3 tag as follows.
<h3>HTML Rendering problem??</h3>.
It displays it correctly when I do not hover over it or try to edit it. But If I hover, the whole background becomes white making it difficult to read the text. Same thing when I click on it to edit. I can see the green open h3 and close h3 but the background is white due to which the text dissolves into it making it difficult to edit it to.
<img width="945" alt="html rendering" src="https://user-images.githubusercontent.com/28474117/51519197-1f302800-1dd5-11e9-8d3e-33289255157f.png">

[Video](https://www.dropbox.com/s/o9s57xwsp6x7lo4/html%20problem.mov?dl=0) for the bug so you can see what I'm talking about.

**Comment by blinkfox** [comment]
Hello, It is the style of the Typora editor. I probably simulated and debugged it. You need to override some styles, the style is as follows:

```css
.md-rawblock-control:not(.md-rawblock-tooltip) {
    /* Your own css properties. */
    background: #666;
    color: #fff;
}

.md-rawblock-on-edit>.md-rawblock-tooltip, .md-rawblock:hover>.md-rawblock-container, .md-rawblock:hover>.md-rawblock-tooltip {
    /* Your own css properties. */
    background: #666;
    color: #fff;
}
```

![snip20190122_1](https://user-images.githubusercontent.com/4027734/51522346-1d617580-1e64-11e9-8c58-5a1e6579a831.png)
![snip20190122_2](https://user-images.githubusercontent.com/4027734/51522348-1dfa0c00-1e64-11e9-9808-8601a992bafe.png)
