### ISSUE TITLE
无法将字体设为Noto Serif显示

### ISSUE THREAD

**Issue by ZongchengMa** [blinkfox/typora-vue-theme#19]
我用过如下两种方法，但显示效果为只有英文和阿拉伯数字可以以Noto Serif来渲染，而中文不行。

第一种方法
```@font-face {
    font-family: Noto Serif;
    font-style: normal;
    font-weight: 600;
    src: local('Noto Serif SC Regular'), url('vue/NotoSerifSC-Regular.otf') format('otf');
}
```body {
    font-family: Source Sans Pro, Helvetica Neue, Arial, sans-serif !important;
    color: #34495e;
    -webkit-font-smoothing: antialiased;
    line-height: 1.6rem;
    letter-spacing: 0;
    margin: 0;
    overflow-x: hidden;
}
```
第二种方法：
将所有引用了本地Source Sans Pro的本地地址改为Noto Serif 的本地地址，如：
```
@font-face {
    font-family: 'Source Sans Pro';
    font-style: normal;
    font-weight: 600;
    src: local('Source Sans Pro SemiBold'), local('SourceSansPro-SemiBold'), url('vue/NotoSerifSC-SemiBold.otf') format('otf');
    /* src: local('Source Sans Pro SemiBold'), local('SourceSansPro-SemiBold'), url('vue/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwmRduz8A.woff2') format('woff2'); */
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```

**Comment by blinkfox** [comment]
@ZongchengMa 我试了下，可以的。

我在[这里](https://github.com/googlei18n/noto-cjk)下载了 `NotoSerifSC-Regular.otf` 字体，放在了主题的 `vue` 文件夹中，将这个字体也在本地电脑中安装了，然后在 `vue.css` 里面添加下面的 css

```css
@font-face {
    font-family: 'Noto Serif SC';
    font-style: normal;
    font-weight: 300;
    src: local('Noto Serif SC'), local('Noto Serif SC Regular'), url('vue/NotoSerifSC-Regular.otf') format('otf');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

修改 body 中的 `font-family` ，添加字体:

```css
body {
    font-family: Noto Serif SC, Source Sans Pro, Helvetica Neue, Arial, sans-serif !important;
    color: #34495e;
    -webkit-font-smoothing: antialiased;
    line-height: 1.6rem;
    letter-spacing: 0;
    margin: 0;
    overflow-x: hidden;
}
```

重启 Typora 就可以看到一个效果了，这个只是`Regular`风格的，同理你还得加其他几种风格的字体。
