### ISSUE TITLE
heading前面自动显示章节号

### ISSUE THREAD

**Issue by czhiling** [blinkfox/typora-vue-theme#5]
谢谢提供这么好的typora theme。美观实用，而且中文显示效果很赞。

有个功能不知如何实现，我希望在heading前面自动显示章节号，有些theme，例如LostKeys提供这个功能。我不熟悉CSS，所以只好来问问。我是用typora写技术文档，所以这个功能对我挺重要。

**Comment by blinkfox** [comment]
@czhiling 你好，我看了下`LostKeys`的主题，它`1`到`3`级标题前面显示的其实是标题的级别，我也大概实现了一下，但是这种个性化的需求，我就不会提交代码了。我告诉你直接在哪里改吧。

你可以在`vue.css`文件里面第`391`行之后的空白处插入如下的`css`代码（你也可以根据自己的需求修改下面的`css`样式），重启`Typora`或者切换主题，即可看到效果，`css`代码如下：

```css
h1::before {
    content: '#1';
    margin-top: 0.6rem;
}

h2::before {
    content: '#2';
    margin-top: 0.4rem;
}

h3::before {
    content: '#3';
    margin-top: 0.1rem;
}

h1::before,
h2::before,
h3::before {
    color: #42B983;
    position: absolute;
    left: -2.1rem;
    font-weight: 400;
    font-size: 1.2rem;
}
```

显示效果如下：

![Typora Heading Style](http://static.blinkfox.com/typora_heading_01.png)
